# starter code circleCI
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  build_backend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/project/backend
    steps:
      - checkout:
        path: ~/project
      - run: npm i
      - run: npm run lint
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    working_directory: ~/project/frontend
    steps:
      - checkout:
        path: ~/project
      - run: npm i
      - run: npm run lint
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - build_backend:
          requires:
            - print_world
      - build_frontend:
          requires:
            - build_backend

# version: 2.1

# jobs:
#   hello-world:
#     docker:
#       - image: amazon/aws-cli
#     steps:
#       - checkout
#       - run:
#           name: Say Hello
#           command: |
#             echo "Hello World"

# workflows:
#   default:
#     jobs:
#       - hello-world
